apiVersion: v1
data:
  PORT: "3001"
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-01T20:47:37Z"
  name: civilian-service-config
  namespace: kavach
  resourceVersion: "25506"
  uid: 99ef579f-6c8b-45f9-87b3-904aab3af6cc
