apiVersion: v1
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9tZWh0YWRldjkyOmRldjEyM0BjbHVzdGVyMC5rN3R5ZHMwLm1vbmdvZGIubmV0L2NpdmlsaWFuLXNlcnZpY2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  SECRET_KEY: c2VjcmV0X2tleQ==
kind: Secret
metadata:
  creationTimestamp: "2025-01-01T20:48:16Z"
  name: civilian-secret
  namespace: kavach
  resourceVersion: "25544"
  uid: ec58cadd-a1d7-4403-943a-37c147e5a865
type: Opaque
