apiVersion: v1
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9tZWh0YWRldjkyOmRldjEyM0BjbHVzdGVyMC5rN3R5ZHMwLm1vbmdvZGIubmV0L3VzZXItc2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  SECRET_KEY: c2VjcmV0X2tleQ==
kind: Secret
metadata:
  creationTimestamp: "2025-01-01T20:40:46Z"
  name: user-secret
  namespace: kavach
  resourceVersion: "25116"
  uid: 77bdf5ac-99d4-4df4-8797-740592222e9c
type: Opaque
