apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-service
  namespace: kavach
  labels:
    app: case-service

#Auto scaling - Auto Healing specifications
spec:   
  replicas: 2
  selector:
    matchLabels:
      app: case-service
  template:
    metadata:
      labels:
        app: case-service
    spec:
      containers:
        - name: case-service
          image: devmehta22/kavach-backend-case-service:latest
          ports:
            - containerPort: 3005
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: case-service-config
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: case-secret
                  key: MONGO_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: case-secret
                  key: SECRET_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: case-service
  namespace: kavach
spec:
  selector:
    app: case-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: ClusterIP

            