apiVersion: v1
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9tZWh0YWRldjkyOmRldjEyM0BjbHVzdGVyMC5rN3R5ZHMwLm1vbmdvZGIubmV0L2Nhc2Utc2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  SECRET_KEY: c2VjcmV0X2tleQ==
kind: Secret
metadata:
  creationTimestamp: "2025-01-01T20:49:35Z"
  name: case-secret
  namespace: kavach
  resourceVersion: "25618"
  uid: 9f983542-ad5f-466a-b148-ec29ccf0da53
type: Opaque
